org.gradle.jvmargs=-Xmx2048M

minecraft_version=b1.7.3
minecraft_version_lower_bound=b1.7.3

fabric_enabled=true

issue_url=https://github.com/SchmarrnDevs/Lighty/issues

mod_version=3.0.2
maven_group=dev.schmarrn
mod_name=Lighty

fabric_loader_version=0.16.14

modmenu_version = 0.3.1+mcb1.7.3

feather_build = 23
raven_build = 2
sparrow_build = 2
nests_build = 7

osl_version = 0.16.3
mod_id=lighty
mod_license=Apache-2.0
mod_authors=andi_makes, agnor99, Alveel
mod_description=The Light Overlay Mod with a twist!