org.gradle.jvmargs=-Xmx2G

# Loader
loader_version = 0.17.0
feather_build = 23
raven_build = 2
sparrow_build = 2
nests_build = 7

# Other Mods
minecraft_version = b1.7.3
mod_menu_version=0.3.1+mcb1.7.3
osl_version = 0.16.3
legacy_lwjgl_3_version=1.2.6-beta.6+b1.7.3

# Mod
mod_version=1.0.0
mod_group=dev.schmarrn.lighty
mod_name=lighty
